import express from 'express';

const router = express.Router();

// Server-side Verified Emergency Numbers Directory
// Official national emergency numbers (never hallucinated or generated by AI)
const OFFICIAL_DIRECTORY = [
  { number: '112', name: 'Unified Emergency Response', desc: 'Single national emergency number (Police, Fire, Medical)', isPrimary: true },
  { number: '100', name: 'Police', desc: 'Police Control Room & Immediate Law Enforcement' },
  { number: '101', name: 'Fire', desc: 'Fire Brigade & Hazard Rescue' },
  { number: '108', name: 'Ambulance', desc: 'Emergency Medical Services & Trauma Ambulance' },
  { number: '1098', name: 'Child Helpline', desc: 'Child Protection & Emergency Rescue' },
  { number: '1930', name: 'Cyber Crime Helpline', desc: 'Financial Fraud & Cyber Incident Response' },
];

const HELPLINE_DIRECTORY = {
  'ACCIDENT': { primary: '112', name: 'Unified Emergency Response', alt: '108' },
  'FIRE': { primary: '112', name: 'Unified Emergency Response', alt: '101' },
  'MEDICAL': { primary: '112', name: 'Unified Emergency Response', alt: '108' },
  'POLICE': { primary: '100', name: 'Police Control Room', alt: '112' },
  'WOMEN_SAFETY': { primary: '112', name: 'Unified Emergency Response', alt: '181' },
  'CHILD_SAFETY': { primary: '1098', name: 'Child Helpline', alt: '112' },
  'FLOOD': { primary: '112', name: 'Unified Emergency Response', alt: '1070' },
  'DISASTER': { primary: '112', name: 'Unified Emergency Response', alt: '1070' },
  'ELECTRICAL': { primary: '112', name: 'Unified Emergency Response', alt: '101' },
  'CYBER': { primary: '1930', name: 'Cyber Crime Helpline', alt: '112' },
  'OTHER': { primary: '112', name: 'Unified Emergency Response', alt: null }
};

const handleHelplineRequest = (req, res) => {
  try {
    const category = req.query.category?.toUpperCase() || 'OTHER';
    const mapping = HELPLINE_DIRECTORY[category] || HELPLINE_DIRECTORY['OTHER'];
    
    res.json({
      success: true,
      category,
      helpline: mapping.primary || '112',
      name: mapping.name || 'Unified Emergency Response',
      altNumber: mapping.alt,
      verified: true,
      directory: OFFICIAL_DIRECTORY,
      verifiedAt: new Date().toISOString()
    });
  } catch (err) {
    console.error('Helpline error:', err);
    res.status(500).json({ 
      success: false, 
      helpline: '112',
      name: 'Unified Emergency Response',
      directory: OFFICIAL_DIRECTORY,
      error: 'Failed to fetch verified helpline.' 
    });
  }
};

router.get('/', handleHelplineRequest);
router.get('/verified', handleHelplineRequest);

export default router;
